apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: amrit
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web
        image: docker.io/amritrathore/test:amrit-webserver-1.0
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "database-service"
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: amrit
spec:
  type: LoadBalancer
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
